name: Passing Secrets
on:
  # Allows you to run the workflow manually from Actions tab
  workflow_dispatch:

jobs:
  # Job 1: Read a secret
  github-secrets:
    runs-on: macOS
    name: A Job to read a secret
    steps:
      # Step 1: Read secret
      - id: read-secret
        shell: bash
        runs: |
          OUR_SECRET=${{ secrets.MY_SECRET  }};
          echo "our-secret=$OUR_SECRET" >> $GITHUB_OUTPUT
    outputs:
      read-secret: ${{ steps.read-secret.outputs.our-secret}}

  # Job 2: Use secret
  use-secret:
    needs: github-secrets
    runs-on: macOS
    name: A Job to use secret
    steps:
      # Step 1: Print our secret
      - id: print-secret
        shell: bash
        runs: echo ${{ needs.github-secrets.outputs.read-secret}}
